<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e1f60fad-14a4-4ac2-aea5-220b1e43540d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
  </ItemGroup>

</Project>
